// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static   FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-vFfBQNZiGrCdkaCmxM-jKCHk1rRl4A',
    appId: '1:27854129571:web:8fea18c707922b489c7216',
    messagingSenderId: '27854129571',
    projectId: 'scopestore-e1870',
    authDomain: 'scopestore-e1870.firebaseapp.com',
    storageBucket: 'scopestore-e1870.firebasestorage.app',
    measurementId: 'G-2CP9WRWQJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj-54frGPJ68c-MT1h2uh_F2eVNo0lcI',
    appId: '1:27854129571:android:29d46212d676a2999c7216',
    messagingSenderId: '27854129571',
    projectId: 'scopestore-e1870',
    storageBucket: 'scopestore-e1870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4IWxVVAX_XLI67Bn0QwYJdvog4yPyuR8',
    appId: '1:27854129571:ios:34c5bae32e30d13d9c7216',
    messagingSenderId: '27854129571',
    projectId: 'scopestore-e1870',
    storageBucket: 'scopestore-e1870.firebasestorage.app',
    iosBundleId: 'com.scopestore.scopeStore',
  );
}
